yolo_model: yolov8s.pt
device: 0    # instead of cpu
conf_threshold: 0.25
iou_threshold: 0.5
package_classes: ["backpack","handbag","suitcase","book"]
person_class: "person"
nearby_distance_px: 180
presence_min_frames: 10
disappear_window_s: 5.0
fps_assume: 25
use_roi_presence: true
package_roi: [[680,550],[950,550],[950,720],[680,720]]
roi_presence_min: 12.0
proximity_grace_last_n: 6
